<<<<<<< develop
# Generated by Django 2.1.1 on 2018-09-06 21:26
=======
# Generated by Django 2.1.1 on 2018-09-08 03:06
>>>>>>> Implementación Inicial Login y Registro de Usuarios

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< develop
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('current_amount', models.IntegerField()),
                ('product_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('registration_date', models.DateField()),
=======
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('A', 'Administrator'), ('E', 'Employee')], max_length=1)),
                ('user_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
>>>>>>> Implementación Inicial Login y Registro de Usuarios
            ],
        ),
    ]
