# Generated by Django 2.1.1 on 2018-09-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('A', 'Administrator'), ('E', 'Employee')], max_length=1)),
                ('user_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
