# Generated by Django 2.1.1 on 2018-09-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('current_amount', models.IntegerField()),
                ('product_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
