# Generated by Django 2.1.1 on 2018-09-09 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storageManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('current_amount', models.IntegerField()),
                ('product_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('registration_date', models.DateField(default=datetime.date(2018, 9, 9))),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('supplier_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('registration_date', models.DateField(default=datetime.date(2018, 9, 9))),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='id_movement',
        ),
        migrations.AlterField(
            model_name='movement',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storageManager.Product'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='id_user_register',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movement',
            name='register_date',
            field=models.DateTimeField(default=datetime.date(2018, 9, 9)),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storageManager.Supplier'),
        ),
    ]
