# Generated by Django 2.1.1 on 2018-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_product', models.IntegerField(max_length=10)),
                ('id_registration_user', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('failed_description', models.TextField()),
            ],
        ),
    ]
