# Generated by Django 2.1.1 on 2018-09-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('supplier_state', models.CharField(choices=[('A', 'Activate'), ('D', 'Deactivate')], max_length=1)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
