# Generated by Django 2.1.1 on 2018-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageManager', '0002_defectiveproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectiveproducts',
            name='id_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='defectiveproducts',
            name='id_registration_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='defectiveproducts',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
